// src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  formulario! : FormGroup

  constructor(
    private formBuilder : FormBuilder
  ) { }

  ngOnInit(): void {
    this.formulario = this.formBuilder.group({
      Email : [''],
      Senha : ['']
    })
  }

  login() : void{
    console.log(this.formulario);
  }

}

<div class="container">
  <div class="left-box-login">
    <img class='logo-redondo-login' src="../../../assets/Logo-Redondo.svg" alt="Logo Redonda" />

    <div class="box-text-login">
      <p class="text-login">Nossa plataforma foi desenvolvida para simplificar e otimizar o processo de
        gerenciamento de lotes e geração de certificados. Com recursos intuitivos e eficientes, estamos aqui para
        facilitar o seu trabalho.</p>
      <p class="text-login">Caso não tenha uma conta clique no botão abaixo e crie uma para acessar todas as
        funcionalidades disponíveis. Nossa interface simples e objetiva proporcionará uma experiência fluida e agradável
        durante toda a sua jornada.</p>
    </div>

    <button class="btn-redirect">Cadastrar</button>
  </div>

  <div class="right-box-login">
      <img class='logo-login' src="../../../assets/Logo.svg" alt="Logo"/>
      <form class='form-login' [formGroup]="formulario">
          <app-input-default [formulario]="formulario" class="input-login" [labelInput]="'Email'" [type]="'email'" [placeholder]="'Digite seu email'" ></app-input-default>
          <app-input-default
          [formulario]="formulario"
          class="input-login"
          [labelInput]="'Senha'"
          [type]="'password'"
          [placeholder]="'Digite sua senha'"></app-input-default>

        <button (click)="login()" class="btn-default">Entrar</button>
      </form>
  </div>

</div>

// src/pages/Login/Login.tsx
import { Button } from '../../components/Button/Button'
import { Input } from '../../components/Input/Input'
import { Container } from '../../components/StructureHome/Container'
import { LeftBox } from '../../components/StructureHome/LeftBox'
import { RightBox } from '../../components/StructureHome/RightBox'
import {Text} from '../../components/Text/Text'
import './login.css'

export function Login() {

    const teste = (e:React.FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        console.log('teste')
    }

  return (
    <>
        <Container>
            <LeftBox path='/cadastro' content='Cadastrar'>
                <Text>Nossa plataforma foi desenvolvida para simplificar e otimizar o processo de gerenciamento de lotes e geração de certificados. Com recursos intuitivos e eficientes, estamos aqui para facilitar o seu trabalho.</Text>
                <Text>
Caso não tenha uma conta clique no botão abaixo e crie uma para acessar todas as funcionalidades disponíveis. Nossa interface simples e objetiva proporcionará uma experiência fluida e agradável durante toda a sua jornada.</Text>
            </LeftBox>

            <RightBox api={teste}>
                <Input.InputDefault moreClassName='input-login' labelInput='Email' placeholder='Digite seu email' type='email' required/>
                <Input.InputDefault moreClassName='input-login' labelInput='Password' placeholder='Digite sua senha' type='password' required/>

                <Button.ButtonDefault content='Entrar' type='submit'/>
            </RightBox>
        </Container>
        
    </>
  )
}
